### ISSUE TITLE
For windows users:

### ISSUE THREAD

**Issue by collinetnickk** [semperai/basic-openai-api-wrapper#3]
The commands are slightly different and include:

git clone https://github.com/semperai/basic-openai-api-wrapper.git

cd basic-openai-api-wrapper

python -m venv venv

venv\Scripts\activate

pip install -r requirements.txt

Then to run it it's simply:

flask run

**Comment by kende** [comment]
Did that, but ran into an error: 

Exception:  [!] No espeak backend found. Install espeak-ng or espeak to your system.
